version: "3"

services:
    postgres:
        image: postgres:9
        ports:
            - 5432:5432
        environment:
            - "POSTGRES_PASSWORD=postgres" 

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - 80:80 
        environment:
            - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
            - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"
